"""create initial catalog supplier tables

Revision ID: da757d56fbd8
Revises: 
Create Date: 2026-06-22 20:09:55.155042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da757d56fbd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_manufacturers_normalized_name'))
    )
    op.create_index('ix_manufacturers_is_active', 'manufacturers', ['is_active'], unique=False)
    op.create_table('material_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('normalized_slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['material_categories.id'], name=op.f('fk_material_categories_parent_id_material_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_categories'))
    )
    op.create_index('ix_material_categories_is_active', 'material_categories', ['is_active'], unique=False)
    op.create_index('ix_material_categories_normalized_slug', 'material_categories', ['normalized_slug'], unique=False)
    op.create_index('ix_material_categories_parent_id', 'material_categories', ['parent_id'], unique=False)
    op.create_index('uq_material_categories_parent_normalized_slug', 'material_categories', ['parent_id', 'normalized_slug'], unique=True, postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.create_index('uq_material_categories_top_level_normalized_slug', 'material_categories', ['normalized_slug'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('account_reference', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_suppliers_normalized_name'))
    )
    op.create_index('ix_suppliers_is_active', 'suppliers', ['is_active'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_type', sa.String(length=40), nullable=False),
    sa.Column('base_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('conversion_factor_to_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units_of_measure.id'], name=op.f('fk_units_of_measure_base_unit_id_units_of_measure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units_of_measure')),
    sa.UniqueConstraint('code', name=op.f('uq_units_of_measure_code'))
    )
    op.create_index('ix_units_of_measure_is_active', 'units_of_measure', ['is_active'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('manufacturer_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_brands_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index('ix_brands_is_active', 'brands', ['is_active'], unique=False)
    op.create_index('ix_brands_manufacturer_id', 'brands', ['manufacturer_id'], unique=False)
    op.create_index('ix_brands_normalized_name', 'brands', ['normalized_name'], unique=False)
    op.create_index('uq_brands_manufacturer_normalized_name', 'brands', ['manufacturer_id', 'normalized_name'], unique=True, postgresql_where=sa.text('manufacturer_id IS NOT NULL'))
    op.create_index('uq_brands_no_manufacturer_normalized_name', 'brands', ['normalized_name'], unique=True, postgresql_where=sa.text('manufacturer_id IS NULL'))
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('manufacturer_id', sa.BigInteger(), nullable=True),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer_model_number', sa.String(length=160), nullable=True),
    sa.Column('default_uom_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['material_categories.id'], name=op.f('fk_products_category_id_material_categories')),
    sa.ForeignKeyConstraint(['default_uom_id'], ['units_of_measure.id'], name=op.f('fk_products_default_uom_id_units_of_measure')),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_products_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index('ix_products_brand_id', 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_manufacturer_id', 'products', ['manufacturer_id'], unique=False)
    op.create_index('ix_products_normalized_name', 'products', ['normalized_name'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_name', sa.String(length=240), nullable=False),
    sa.Column('normalized_variant_name', sa.String(length=240), nullable=False),
    sa.Column('manufacturer_variant_code', sa.String(length=160), nullable=True),
    sa.Column('default_purchase_uom_id', sa.BigInteger(), nullable=True),
    sa.Column('default_usage_uom_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_purchase_uom_id'], ['units_of_measure.id'], name=op.f('fk_product_variants_default_purchase_uom_id_units_of_measure')),
    sa.ForeignKeyConstraint(['default_usage_uom_id'], ['units_of_measure.id'], name=op.f('fk_product_variants_default_usage_uom_id_units_of_measure')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants'))
    )
    op.create_index('ix_product_variants_is_active', 'product_variants', ['is_active'], unique=False)
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('uq_product_variants_product_normalized_variant_name', 'product_variants', ['product_id', 'normalized_variant_name'], unique=True)
    op.create_table('supplier_product_listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=160), nullable=True),
    sa.Column('normalized_supplier_sku', sa.String(length=160), nullable=True),
    sa.Column('supplier_model_number', sa.String(length=160), nullable=True),
    sa.Column('listing_name', sa.String(length=260), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('purchase_uom_id', sa.BigInteger(), nullable=True),
    sa.Column('package_quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('package_uom_id', sa.BigInteger(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_uom_id'], ['units_of_measure.id'], name=op.f('fk_supplier_product_listings_package_uom_id_units_of_measure')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_supplier_product_listings_product_variant_id_product_variants')),
    sa.ForeignKeyConstraint(['purchase_uom_id'], ['units_of_measure.id'], name=op.f('fk_supplier_product_listings_purchase_uom_id_units_of_measure')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_product_listings_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_product_listings'))
    )
    op.create_index('ix_supplier_product_listings_is_active', 'supplier_product_listings', ['is_active'], unique=False)
    op.create_index('ix_supplier_product_listings_normalized_supplier_sku', 'supplier_product_listings', ['normalized_supplier_sku'], unique=False)
    op.create_index('ix_supplier_product_listings_product_variant_id', 'supplier_product_listings', ['product_variant_id'], unique=False)
    op.create_index('ix_supplier_product_listings_supplier_id', 'supplier_product_listings', ['supplier_id'], unique=False)
    op.create_index('ix_supplier_product_listings_supplier_sku', 'supplier_product_listings', ['supplier_sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_product_listings_supplier_sku', table_name='supplier_product_listings')
    op.drop_index('ix_supplier_product_listings_supplier_id', table_name='supplier_product_listings')
    op.drop_index('ix_supplier_product_listings_product_variant_id', table_name='supplier_product_listings')
    op.drop_index('ix_supplier_product_listings_normalized_supplier_sku', table_name='supplier_product_listings')
    op.drop_index('ix_supplier_product_listings_is_active', table_name='supplier_product_listings')
    op.drop_table('supplier_product_listings')
    op.drop_index('uq_product_variants_product_normalized_variant_name', table_name='product_variants')
    op.drop_index('ix_product_variants_product_id', table_name='product_variants')
    op.drop_index('ix_product_variants_is_active', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_products_normalized_name', table_name='products')
    op.drop_index('ix_products_manufacturer_id', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_brand_id', table_name='products')
    op.drop_table('products')
    op.drop_index('uq_brands_no_manufacturer_normalized_name', table_name='brands', postgresql_where=sa.text('manufacturer_id IS NULL'))
    op.drop_index('uq_brands_manufacturer_normalized_name', table_name='brands', postgresql_where=sa.text('manufacturer_id IS NOT NULL'))
    op.drop_index('ix_brands_normalized_name', table_name='brands')
    op.drop_index('ix_brands_manufacturer_id', table_name='brands')
    op.drop_index('ix_brands_is_active', table_name='brands')
    op.drop_table('brands')
    op.drop_index('ix_units_of_measure_is_active', table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index('ix_suppliers_is_active', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('uq_material_categories_top_level_normalized_slug', table_name='material_categories', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index('uq_material_categories_parent_normalized_slug', table_name='material_categories', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_index('ix_material_categories_parent_id', table_name='material_categories')
    op.drop_index('ix_material_categories_normalized_slug', table_name='material_categories')
    op.drop_index('ix_material_categories_is_active', table_name='material_categories')
    op.drop_table('material_categories')
    op.drop_index('ix_manufacturers_is_active', table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
